stages:
  - build
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - cd project/tci-final/api
    - gradlew.bat build --stacktrace
    - cd ..
    - cd api
    - gradlew.bat build --stacktrace
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test:
  stage: test
  script:
    - cd project/tci-final/api
    - gradlew.bat test
    - cd ..
    - cd api
    - gradlew.bat test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

after_script:
  - echo "End CI"