
stages:
    - build
    - test
    - deploy
        
build:
  tags:
  - Maria
  stage: build
  script: 
  - cd project/tci-final/logic
  - gradlew.bat build --info
  - cd ../api
  - gradlew.bat build --info
  allow_failure: true
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
      
test:
  tags:
  - Maria, tci
  stage: test
  script: 
  - cd project/tci-final/logic
  - gradlew.bat test --info
  - gradlew.bat jacocoTestReport --info
  - cd ../api
  - gradlew.bat test --info
  - gradlew.bat jacocoTestReport --info
  - gradlew.bat jmRun
  - gradlew.bat jmReport
  allow_failure: true
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    when: always
    paths:
        - /m_andreeva/tci-group-assignment/project/tci-final/logic/build/test-results/test
        - /m_andreeva/tci-group-assignment/project/tci-final/logic/build/reports/tests/test
        - /m_andreeva/tci-group-assignment/project/tci-final/logic/build/jacocoHtml
        - /m_andreeva/tci-group-assignment/project/tci-final/api/build/test-results/test
        - /m_andreeva/tci-group-assignment/project/tci-final/api/build/reports/tests/test
        - /m_andreeva/tci-group-assignment/project/tci-final/api/build/jacocoHtml
        - /m_andreeva/tci-group-assignment/project/tci-final/api/build/jmeter-report
  
pages:
    tags:
    - Maria, tci
    stage: deploy
    dependencies:
    - test
    script:
    - cd project\tci-final\api
    - gradlew.bat war
    - ../scripts/deployWar.ps1
    - cd ../../../
    - md .public
    - md .public\logic
    - md .public\logic_jacoco
    - md .public\logic_stylecheck
    - xcopy project\tci-final\logic\build\reports\tests\test\* .public\logic
    - xcopy project\tci-final\logic\build\jacocoHtml\* .public\logic_jacoco
    - md .public\api
    - md .public\api_jacoco
    - md .public\api_stylecheck
    - xcopy project\tci-final\api\build\reports\tests\test\* .public\api
    - xcopy project\tci-final\api\build\jacocoHtml\* .public\api_jacoco
    - xcopy project\tci-final\api\build\jmeter-report\* .public\jmeter-report
    - mv .public public
    allow_failure: true
    artifacts:
        when: always
        paths:
        - public
    only:
    - dev-ci
