image: gradle:alpine
    
variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  
before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradlew
  
build:
    stage: build
    script:
        - cd project/tci-final/api
        - gradle compileJava --stacktrace
        - cd ..
        - cd logic
        - gradle compileJava --stacktrace
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: pull
        paths:
            - build
            - .gradle

test:
    stage: test
    dependencies:
        - build
    script:
        - gradle check
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: pull
        paths:
            - build
            - .gradle