image: gradle:alpine

stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - cd project/tci-final/api
    - gradle compileJava 
  artifacts:
    paths:
      - build
      - .gradle

test:
  stage: test
  script:
    gradle check


after_script:
  - echo "End CI"