image: gradle:alpine

stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - cd project/tci-final/api
    - gradle build
    - cd ..
    - cd api
    - gradle build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test:
  stage: test
  script:
    - cd project/tci-final/api
    - gradle test
    - cd ..
    - cd api
    - gradle test


after_script:
  - echo "End CI"